canonical/katib-rocks

file-metrics-collector/rockcraft.yaml
ROCK for Katib file-metrics-collector is part of katib-config. Based on https://github.com/canonical/katib-rocks/pull/5
Since configuration is provided when this container is ran in the pod it is expected to fail when running manually. However, it is enough to ensure that service is being started.
- Initial version of file  metrics collector ROCK.
=> feat: file metrics collector rock

earlystopping-medianstop/rockcraft.yaml
ROCK for Katib earlystopping-medianstop is part of katib-config.
Based on https://github.com/canonical/katib-rocks/pull/1
- Updated to use pythong and nil plugins
- Used best practices spec to create rockcraft.yaml
- Tested using manual testing methods.
Since configuration is provided when this container is ran in the pod it is expected to fail when running manually. However, it is enough to ensure that service is being started.
Pebble service:
```
docker run earlystopping-medianstop:v0.15.0_22.04_1 exec pebble restart earlystopping-medianstop
2023-07-18T15:19:59.111Z [pebble] Started daemon.
2023-07-18T15:19:59.127Z [pebble] POST /v1/exec 14.658308ms 202
2023-07-18T15:19:59.142Z [pebble] GET …
```
=> Feat earlystopping medianstop rock

tfevent-metrics-collector/rockcraft.yaml
ROCK for Katib tfevent-metrics-collector is part of katib-config.
Based on https://github.com/canonical/katib-rocks/pull/7
Since configuration is provided when this container is ran in the pod it is expected to fail when running manually. However, it is enough to ensure that service is being started.
- Initial version of TFEvent metrics collector ROCK.
- Updated to use pythong and nil plugins
- Used best practices spec to create rockcraft.yaml
- Tested using manual testing methods.
Pebble service:
```
docker run tfevent-metrics-collector:v0.15.0_22.04_1 exec pebble restart tfevent-metrics-collector
2023-07-18T16:16:41.967Z [pebble] Started daemon.
2023-07-18T16:16:41.981Z [pebble] POST /v1/exec …
```
=> Feat tfevent-metrics-collector rock

katib-controller/rockcraft.yaml
katib-controller ROCK is managed by katib-controller charm. Charm's integration tests should be re-used to test functionality of this ROCK.
- Initial version of the ROCK.
- Created rockcraft file for katib-controller ROCK. ROCK is built and limited manual testing is done.
=> feat: katib-controller rock

katib-db-manager/rockcraft.yaml
Katib ROCKs are part of main epic for building secure images using ROCKs. katib-db-manager ROCK is managed by katib-controller charm. Charm's integration tests should be re-used to test functionality of this ROCK.
- Initial version of the ROCK.
- Created rockcraft file for katib-db-manager ROCK. ROCK is built and limited manual testing is done.
Manual test:
```
docker run katib-db-manager:v0.15.0_22.04_1 exec /app/katib-db-manager
2023-07-18T18:13:48.097Z [pebble] Started daemon.
2023-07-18T18:13:48.197Z [pebble] POST /v1/exec 98.854491ms 202
2023-07-18T18:13:48.198Z [pebble] GET /v1/tasks/1/websocket/control 152.171µs 200
2023-07-18T18:13:48.199Z [pebble] GET /v1/tasks/1/websocket/stdio 104.532µs 200
2023-07-18T18:13:48.199Z [pebble] GET /v1/tasks/1/websocket/stderr …
```
=> feat: katib-db-manager rock

suggestion-hyperband/rockcraft.yaml
Details are in #17
ROCK for Katib suggestion-hyperband is part of katib-config.
Initial version of suggestion-hyperband ROCK.
Manual test:
```
sudo docker run suggestion-hyperband_v0.15.0_22.04_1_amd64:rock exec bash -c 'export PYTHONPATH="/usr/local/lib/python3.10/dist-packages
/:/opt/katib:/opt/katib/pkg/apis/manager/v1beta1/python:/opt/katib/pkg/apis/manager/health/python" && python3 /opt/katib/cmd/suggestion/hyperband/v1beta1/main.py'
2023-08-17T14:04:05.447Z [pebble] Started daemon.
2023-08-17T14:04:05.454Z [pebble] POST /v1/exec 6.412998ms 202
2023-08-17T14:04:05.460Z [pebble] GET /v1/tasks/1/websocket/control 4.956321ms 200
2023-08-17T14:04:05.462Z [pebble] GET /v1/tasks/1/websocket/stdio 140.314µs 200 …
```
=> feat: add suggestion-hyperband rock

suggestion-enas/rockcraft.yaml
Details are in #17
ROCK for Katib suggestion-enas is part of katib-config.
Initial version of suggestion-enas ROCK.
**Note:** no need to keep GRPC binary from v0.15.0, since this type of ROCK images are not managed by charms.
GRPC checks will be peformed by K8S on this images.
=> feat: add suggestion-nas-enas rock

suggestion-goptuna/rockcraft.yaml
Part of #17
Details are in https://github.com/canonical/katib-rocks/issues/17
base on #9 
ROCK for Katib suggestion-goptuna is part of katib-config.
Initial version of suggestion-goptuna ROCK.
Manual test:
```
sudo docker run --rm suggestion-goptuna:rock exec bash -c './goptuna-suggestion'
```
Pebble service
```
sudo docker run --rm suggestion-goptuna:rock exec pebble restart suggestion-goptuna
```
=> feat: add suggestion goptuna rock

suggestion-nas-darts/rockcraft.yaml
The tag that was in the rockcraft project did not match any of the upstream tags, preventing the rock to be built. Adding the correct tag.
=> fix: fix git tag for suggestion-nas-darts

katib-ui-rock/rockcraft.yaml
Previously, an older version of the katib-ui had been rocked.  This commit updates the rock to the current katib-ui, replicating the build defined by https://github.com/kubeflow/katib/blob/v0.16.0/cmd/ui/v1beta1/Dockerfile
Note:
* the version of the frontend-lib pulled here is that specified by the katib repo in the [COMMIT](https://github.com/kubeflow/katib/blob/v0.16.0/pkg/ui/v1beta1/frontend/COMMIT) file of the upstream repo
* the GOARCH is omitted from building here because upstream also omits this.  This might be something to revisit later, or might be something determined in different ways in rocks anyway?
Closes #32 
Do:
```bash
VERSION=version_in_rockcraft_file
rockcraft pack
skopeo --insecure-policy copy oci-archive:katib-ui_${VERSION}_amd64.rock docker-daemon:katib-ui:${VERSION} …
```
=> update katib-ui rockcraft.yaml

README.md, earlystopping-medianstop/README.md
This commit replaces ROCKs with rocks to be in sync with Canonical's standard terminology.
Part of canonical/bundle-kubeflow#916
=> chore: replace ROCKs with rocks

katib-ui-rock/rockcraft.yaml, katib-ui-rock/tests/test_rock.py, katib-ui-rock/tox.ini
---
- Added tests
- Added tox.ini
=> Updated `katib-ui-rock`

suggestion-enas/rockcraft.yaml
Closes: https://github.com/canonical/katib-rocks/issues/50
Add correct permissions for the user in the rock.
How to test:
```
cd suggestion-enas
rockcraft clean && rockcraft pack --verbosity=trace --debug 
sudo rockcraft.skopeo --insecure-policy copy oci-archive:suggestion-enas_v0.17.0_amd64.rock docker-daemon:misohu/suggestion-enas:0.17.0
docker run -ti  misohu/suggestion-enas:0.17.0 -v
```
expected output 
```
2024-09-03T13:24:25.749Z [pebble] Started daemon.
2024-09-03T13:24:25.784Z [pebble] POST /v1/services 16.991767ms 202
2024-09-03T13:24:25.800Z [pebble] Service "suggestion-enas" starting: python3 main.py
2024-09-03T13:24:26.093Z [suggestion-enas] 2024-09-03 13:24:26.093490: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different …
```
=> Fix permission in suggestion-enas

suggestion-enas/rockcraft.yaml
Improves the permissions handling on suggestion-enas rock. Based on rockcraft team recommendations.
=> Refactor permissions with dump plugin

earlystopping-medianstop/rockcraft.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6831
Please note that there haven't been updates to the upstream Dockerfile of this rock, therefore this PR only bumps the version and source to keep it up to date with the versioning system.
=> chore: bump source and version of the `earlystopping-medianstop` rock 0.17 -> 0.18

suggestion-enas/rockcraft.yaml, suggestion-enas/tox.ini
Based on: https://github.com/kubeflow/katib/blob/v0.18.0-rc.0/cmd/suggestion/nas/enas/v1beta1/Dockerfile.
Note that there weren't any changes.
=> chore: update suggestion-enas rock to v0.18.0-rc.0

suggestion-goptuna/rockcraft.yaml, suggestion-goptuna/tox.ini
Based on the upstream file: https://github.com/kubeflow/katib/blob/v0.17.0/cmd/suggestion/goptuna/v1beta1/Dockerfile
=> chore: update goptuna rock to `v0.18.0-rc.0`

suggestion-hyperband/rockcraft.yaml, suggestion-hyperband/tox.ini
Based on the upstream file: https://github.com/kubeflow/katib/blob/v0.18.0-rc.0/cmd/suggestion/hyperband/v1beta1/Dockerfile
=> chore: update hyperband rock to v0.18.0-rc.0

suggestion-hyperopt/rockcraft.yaml, suggestion-hyperopt/tox.ini
Based on the upstream image: https://github.com/kubeflow/katib/blob/v0.17.0/cmd/suggestion/hyperopt/v1beta1/Dockerfile
=> chore: update hyperopt rock to v0.18.0-rc.0

katib-controller/rockcraft.yaml
Bump the rock 0.17 -> 0.18.0-rc.0 in preparation for a new release.
Please note that there haven't been updates to the upstream Dockerfile of this rock, therefore this PR only bumps the version and source to keep it up to date with the versioning system.
=> chore: bump source and version of the rock 0.17 -> 0.18

katib-ui-rock/rockcraft.yaml
Bump the rock 0.17 -> 0.18.0-rc.0 in preparation for a new release.
The `diff` shows the following differences between the two versions of upstream Dockerfiles:
```diff
< FROM ubuntu AS fetch-kubeflow-kubeflow
---
> FROM alpine/git AS fetch-kubeflow-kubeflow
4,5d3
< RUN apt-get update && apt-get install git -y
<
14c12
< FROM node:12 AS frontend-kubeflow-lib
---
> FROM node:16-alpine AS frontend-kubeflow-lib
20c18,25
< RUN npm ci
---
> RUN npm config set fetch-retry-mintimeout 200000 && \
>     npm config set fetch-retry-maxtimeout 1200000 && \
>     npm config get registry && \
>     npm config set registry https://registry.npmjs.org/ && \
>     npm config delete https-proxy && \
>     npm config set loglevel verbose && \
>     npm cache clean --force && \
>     npm ci --force …
```
=> chore: bump katib-ui 0.17 -> 0.18.0-rc.0

earlystopping-medianstop/rockcraft.yaml, katib-controller/rockcraft.yaml, katib-db-manager/rockcraft.yaml, katib-ui-rock/rockcraft.yaml, suggestion-enas/rockcraft.yaml, suggestion-goptuna/rockcraft.yaml, suggestion-hyperband/rockcraft.yaml, suggestion-hyperopt/rockcraft.yaml, suggestion-nas-darts/rockcraft.yaml, suggestion-optuna/rockcraft.yaml, suggestion-pbt/rockcraft.yaml, suggestion-skopt/rockcraft.yaml
Closes https://warthogs.atlassian.net/browse/KF-7151
No changes in the images, just updated the version. See the [diff](https://github.com/kubeflow/katib/compare/v0.18.0-rc.0...v0.18.0) for reference.
=> chore: upgrade rocks from 0.18.0-rc to 0.18.0

.github/workflows/on_workflow_dispatch.yaml, katib-controller/rock-ci-metadata.yaml
Closes: https://github.com/canonical/katib-rocks/issues/87
This pr: 
- introduces `rock-ci-metadata.yaml` file for rock integration.
- add `workflow_dispatch` job for manual rock integration.
For full file creation steps please refer to [this](https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114) comment.
=> feat: `katib-controller` create rocks-automation-ci.yaml
